# Generated by Django 4.2.30 on 2026-09-12 12:31

import assessment.clock
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(verbose_name='责任开始')),
                ('valid_to', models.DateTimeField(blank=True, help_text='为空表示长期有效', null=True, verbose_name='责任结束')),
                ('base_penalty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单起问题基础扣分')),
                ('overdue_daily_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='逾期每日加扣')),
                ('rectify_sla_hours', models.PositiveIntegerField(default=24, verbose_name='整改时限(小时)')),
            ],
            options={
                'ordering': ['grid__code', 'valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='承包商编码')),
                ('name', models.CharField(max_length=128, verbose_name='承包商名称')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '有效'), ('void', '已作废')], default='active', max_length=16, verbose_name='状态')),
                ('void_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='作废原因')),
                ('created_at', models.DateTimeField(default=assessment.clock.now, verbose_name='创建时间')),
                ('contract', models.ForeignKey(blank=True, help_text='按事件发生时的责任区间确定', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_units', to='assessment.cleaningcontract', verbose_name='归属合同')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_units', to='assessment.contractor', verbose_name='归属承包商')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('litter', '暴露垃圾'), ('spill', '渣土遗撒'), ('water', '积水污渍'), ('other', '其他')], default='other', max_length=16, verbose_name='问题类别')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='问题位置')),
                ('occurred_at', models.DateTimeField(help_text='取自首张证据照片的拍摄时间', verbose_name='发生时间')),
                ('status', models.CharField(choices=[('open', '待整改'), ('rectifying', '整改中'), ('rectified', '已整改'), ('void', '已作废')], default='open', max_length=16, verbose_name='状态')),
                ('rectification_deadline', models.DateTimeField(verbose_name='整改期限')),
                ('rectified_at', models.DateTimeField(blank=True, null=True, verbose_name='整改完成时间')),
                ('void_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='作废原因')),
                ('created_at', models.DateTimeField(default=assessment.clock.now, verbose_name='录入时间')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RoadGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='网格编码')),
                ('name', models.CharField(max_length=128, verbose_name='网格名称')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='网格范围')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RectificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='幂等键')),
                ('reported_at', models.DateTimeField(verbose_name='整改上报时间')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('received_at', models.DateTimeField(default=assessment.clock.now, verbose_name='接收时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rectification_reports', to='assessment.problemevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='problemevent',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assessment.roadgrid', verbose_name='所属网格'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence/%Y/%m/', verbose_name='照片')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='精确指纹')),
                ('phash_hex', models.CharField(max_length=16, verbose_name='感知哈希')),
                ('taken_at', models.DateTimeField(verbose_name='拍摄时间')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='拍摄位置')),
                ('status', models.CharField(choices=[('linked', '已关联事件'), ('void', '已作废')], default='linked', max_length=16, verbose_name='状态')),
                ('uploaded_at', models.DateTimeField(default=assessment.clock.now, verbose_name='上传时间')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='assessment.problemevent', verbose_name='关联事件')),
            ],
            options={
                'ordering': ['taken_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('base_points', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基础扣分')),
                ('escalation_points', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='逾期加扣')),
                ('reason', models.CharField(max_length=255, verbose_name='版本说明')),
                ('locked', models.BooleanField(default=False, verbose_name='已锁定')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('created_at', models.DateTimeField(default=assessment.clock.now, verbose_name='创建时间')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assessment.penaltyunit')),
            ],
            options={
                'ordering': ['unit_id', 'version'],
            },
        ),
        migrations.AddField(
            model_name='penaltyunit',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_unit', to='assessment.problemevent'),
        ),
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_match', models.BooleanField(verbose_name='精确指纹一致')),
                ('hamming_distance', models.PositiveSmallIntegerField(verbose_name='哈希汉明距离')),
                ('distance_m', models.FloatField(verbose_name='拍摄点间距(米)')),
                ('time_gap_seconds', models.BigIntegerField(verbose_name='拍摄时间差(秒)')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('confirmed', '确认同一问题'), ('rejected', '确认非同一问题')], default='pending', max_length=16, verbose_name='状态')),
                ('resolution_note', models.CharField(blank=True, default='', max_length=255, verbose_name='复核意见')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('created_at', models.DateTimeField(default=assessment.clock.now, verbose_name='生成时间')),
                ('photo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_as_a', to='assessment.photo')),
                ('photo_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_as_b', to='assessment.photo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='cleaningcontract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assessment.contractor', verbose_name='承包商'),
        ),
        migrations.AddField(
            model_name='cleaningcontract',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assessment.roadgrid', verbose_name='网格'),
        ),
        migrations.AddConstraint(
            model_name='penaltyversion',
            constraint=models.UniqueConstraint(fields=('unit', 'version'), name='uniq_penalty_version'),
        ),
        migrations.AddConstraint(
            model_name='duplicatecandidate',
            constraint=models.UniqueConstraint(fields=('photo_a', 'photo_b'), name='uniq_candidate_pair'),
        ),
    ]
